SELECT NOW();

SELECT CURDATE();

SELECT CURTIME();

SELECT YEAR(NOW());
SELECT MONTH(NOW());
SELECT DAY(NOW());
SELECT HOUR(NOW());
SELECT MINUTE(NOW());
SELECT SECOND(NOW());

SELECT DAYNAME(NOW());
SELECT MONTHNAME(NOW());

SELECT EXTRACT(DAY FROM NOW());
SELECT EXTRACT(MONTH FROM NOW());
SELECT EXTRACT(YEAR FROM NOW());


SELECT
	*
FROM
	sql_store.orders
WHERE
	YEAR(order_date) = YEAR(NOW());
